import Modals from "@/components/modals"
import Navbar from "@/components/navbar"
import StoreProvider from "@/components/providers"
import Resize from "@/components/resize"
import Socials from "@/components/socials"
import type { Metadata } from "next"
import "./globals.css"

export const metadata: Metadata = {
  icons: ["/assets/mario.png"],
  title: "Mario wanted",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="h-full">
      <body className="h-full m-0 font-mario">
        <StoreProvider>
          <Navbar />
          <Modals />
          {children}
          <Resize />
          <Socials />
        </StoreProvider>
      </body>
    </html>
  )
}
