import StoreProvider from "@/app/providers"
import Modal from "@/components/modal"
import Navbar from "@/components/navbar"
import type { Metadata } from "next"
import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="h-full">
      <body className="h-full m-0 font-mario">
        <StoreProvider>
          <Navbar />
          <Modal />
          {children}
        </StoreProvider>
      </body>
    </html>
  )
}
